### ISSUE TITLE
Add FAQ entry regarding donation vs donation key

### ISSUE THREAD

**Issue by infeo** [cryptomator/cryptomator.github.io#38]
To avoid confusion, see for example: 
https://community.cryptomator.org/t/where-is-my-donation-key/5323/12?u=infeo

**Comment by tobihagemann** [comment]
I don't think that an FAQ entry will solve this issue. We have to improve the design of the donation page.

**Comment by tobihagemann** [comment]
We'll see if the committed changes actually help:

- Replaced third "feature" of "Just donate" with "No donation key" (and a different icon), see ef5c847c225630f3127ae96e0231b54732d5879b
- Put both options in "boxes" to make the separation clearer
- Reduced lead text so that it's more readable (which highlights the separate options again)

A complete redesign of the donation page could still be implemented but for now it's more important to have less confused and frustrated users.
