### ISSUE TITLE
Automate or provide a way to easily update config after a release

### ISSUE THREAD

**Issue by xballoy** [cryptomator/cryptomator.github.io#92]
**Context**: I use brew to update it and my PR to update the casks are always blocked as long as the website gives the previous version even if the release is created.

Could you automate the update of [config.toml](https://github.com/cryptomator/cryptomator.github.io/blob/develop/config.toml) or provide the steps to update it from a Cryptomator release?

Currently I would need to download each files from the release manually, calculate their hash and replace them in the file. A lot of manual steps that could lead to a typo.

**Comment by overheadhunter** [comment]
The mac build is currently stuck due to notarization problems. That said, we don't update the config.toml automatically, because we have a three-step release process:

1. publish the release on github
2. if we don't see problems after smoke testing, we update the release on our website
3. if there still aren't any significant bug reports after 1-2 days, we update the json file that the update checker reads

I would suggest that ideally the brew build wouldn't depend on the toml but rather read required information purely from GitHub releases. We publish pgp signatures along with all binaries that can be verified using [this public key](https://gist.github.com/cryptobot/211111cf092037490275f39d408f461a). Can these be used instead of sha sums? Otherwise we can look into automating sha sum publishing.

**Comment by xballoy** [comment]
Thanks for the feedback and the explanations on the process. That makes even more sense to wait for the website to be updated for the brew cask to be updated. That would prevent bad release to be deployed to many people.

A note regarding brew: they get the builds from the Github release not from the website. The website is used only to check if the version is the latest. I'm not sure how brew get the sha from the release, it probably calculate it itself. I have no idea if they can use pgp to do it.

I will close the issue because you already have a working process (that I didn't know about). Feel free to open it again if you think it needs to.
